image: cmake:latest

stages:
  - build
  - test

before_script:
  - mkdir build
  - cd build
  - cmake ..

build:
  stage: build
  script:
    - make

test:
  stage: test
  script:
    - ctest
    - ./test_factorial