stages :
  - build
  - test

build-project:
  stage : build
  script:
    - mkdir build
    - cd build
    - cmake .. && cmake --build . && make

test-project:
  stage: test
  script:
    - mkdir Step7_build
    - cd Step7_build
    - cmake .. && cmake --build . && make
    - ctest -VV
