set(CTEST_PROJECT_NAME "toya")
set(CTEST_NIGHTLY_START_TIME "01:00:00 UTC")
set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "my.cdash.org")
set(CTEST_DROP_LOCATION "/submit.php?project=toya")
set(CTEST_SITE "MySite")
set(CTEST_BUILD_NAME "Linux-Debug")
set(CTEST_BUILD_COMMAND "cmake --build .")
set(CTEST_CMAKE_GENERATOR "Unix Makefiles")
