version: 2.1

jobs:
  build:
    docker:
      - image: circleci/cpp:latest

    working_directory: ~/project

    steps:
      - checkout

      # Install dependencies
      - run: sudo apt-get update && sudo apt-get install -y build-essential cmake

      # Build the project
      - run: mkdir build && cd build && cmake .. && make

      # Run the tests
      - run: cd build && ctest